begin;

create table if not exists public.themes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (length(trim(name)) > 0),
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, name)
);

create table if not exists public.records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  context text not null check (length(trim(context)) > 0),
  problem text not null check (length(trim(problem)) > 0),
  original_context text not null,
  original_problem text not null,
  original_feeling jsonb not null default '[]'::jsonb check (jsonb_typeof(original_feeling) = 'array'),
  feeling jsonb not null default '[]'::jsonb check (jsonb_typeof(feeling) = 'array'),
  feeling_note text not null default '',
  scene text not null default '其他',
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  pain_score smallint check (pain_score between 1 and 5),
  frequency_score smallint check (frequency_score between 1 and 5),
  time_cost_score smallint check (time_cost_score between 1 and 5),
  current_process text not null default '',
  pain_point text not null default '',
  current_solution text not null default '',
  solution_problem text not null default '',
  desired_state text not null default '',
  input text not null default '',
  output text not null default '',
  repeatability text check (repeatability in ('一次性','偶尔','每月','每周','每天','高频')),
  standardizable text check (standardizable in ('是','部分可以','不确定','否')),
  automation_potential smallint check (automation_potential between 1 and 5),
  usage_intent smallint check (usage_intent between 1 and 5),
  willingness_to_build text check (willingness_to_build in ('不值得','30 分钟','几小时','一两天','一周','长期项目')),
  status text not null default 'Inbox' check (status in ('Inbox','Observing','Candidate','Project','Building','Solved','Archived')),
  related_need bigint references public.themes(id) on delete set null
);

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  name text not null check (length(trim(name)) > 0),
  category text not null default 'custom' check (category in ('scene','problem','custom'))
);

create unique index if not exists tags_system_name_category_unique
  on public.tags (name, category) where user_id is null;
create unique index if not exists tags_user_name_category_unique
  on public.tags (user_id, name, category) where user_id is not null;

create table if not exists public.record_tags (
  record_id bigint not null references public.records(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  primary key (record_id, tag_id)
);

create index if not exists records_user_occurred_idx on public.records (user_id, occurred_at desc);
create index if not exists records_user_theme_idx on public.records (user_id, related_need);
create index if not exists records_user_status_idx on public.records (user_id, status);
create index if not exists record_tags_tag_idx on public.record_tags (tag_id);

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.protect_original_expression()
returns trigger language plpgsql set search_path = '' as $$
begin
  if new.original_context is distinct from old.original_context
     or new.original_problem is distinct from old.original_problem
     or new.original_feeling is distinct from old.original_feeling then
    raise exception 'Original expression is immutable';
  end if;
  return new;
end;
$$;

create or replace function public.validate_theme_owner()
returns trigger language plpgsql set search_path = '' as $$
begin
  if new.related_need is not null and not exists (
    select 1 from public.themes
    where id = new.related_need and user_id = new.user_id
  ) then
    raise exception 'Theme does not belong to this user';
  end if;
  return new;
end;
$$;

drop trigger if exists themes_set_updated_at on public.themes;
create trigger themes_set_updated_at before update on public.themes
for each row execute function public.set_updated_at();

drop trigger if exists records_set_updated_at on public.records;
create trigger records_set_updated_at before update on public.records
for each row execute function public.set_updated_at();

drop trigger if exists records_protect_original on public.records;
create trigger records_protect_original before update on public.records
for each row execute function public.protect_original_expression();

drop trigger if exists records_validate_theme_owner on public.records;
create trigger records_validate_theme_owner before insert or update of related_need, user_id on public.records
for each row execute function public.validate_theme_owner();

alter table public.themes enable row level security;
alter table public.records enable row level security;
alter table public.tags enable row level security;
alter table public.record_tags enable row level security;

create policy "themes_select_own" on public.themes for select to authenticated using ((select auth.uid()) = user_id);
create policy "themes_insert_own" on public.themes for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "themes_update_own" on public.themes for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "themes_delete_own" on public.themes for delete to authenticated using ((select auth.uid()) = user_id);

create policy "records_select_own" on public.records for select to authenticated using ((select auth.uid()) = user_id);
create policy "records_insert_own" on public.records for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "records_update_own" on public.records for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "records_delete_own" on public.records for delete to authenticated using ((select auth.uid()) = user_id);

create policy "tags_select_visible" on public.tags for select to authenticated using (user_id is null or (select auth.uid()) = user_id);
create policy "tags_insert_own" on public.tags for insert to authenticated with check ((select auth.uid()) = user_id and category = 'custom');
create policy "tags_update_own" on public.tags for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id and category = 'custom');
create policy "tags_delete_own" on public.tags for delete to authenticated using ((select auth.uid()) = user_id and category = 'custom');

create policy "record_tags_select_own" on public.record_tags for select to authenticated using (
  exists (select 1 from public.records where records.id = record_id and records.user_id = (select auth.uid()))
);
create policy "record_tags_insert_own" on public.record_tags for insert to authenticated with check (
  exists (select 1 from public.records where records.id = record_id and records.user_id = (select auth.uid()))
  and exists (select 1 from public.tags where tags.id = tag_id and (tags.user_id is null or tags.user_id = (select auth.uid())))
);
create policy "record_tags_delete_own" on public.record_tags for delete to authenticated using (
  exists (select 1 from public.records where records.id = record_id and records.user_id = (select auth.uid()))
);

create or replace function public.delete_own_account()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception 'Authentication required';
  end if;

  delete from auth.users where id = current_user_id;
  if not found then
    raise exception 'Account not found';
  end if;
end;
$$;

revoke all on function public.delete_own_account() from public;
revoke all on function public.delete_own_account() from anon;
grant execute on function public.delete_own_account() to authenticated;

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.themes, public.records, public.tags, public.record_tags to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into public.tags (user_id, name, category) values
  (null, '学习', 'scene'), (null, '科研', 'scene'), (null, '编程', 'scene'),
  (null, '摄影', 'scene'), (null, '生活', 'scene'), (null, '文件管理', 'scene'),
  (null, '信息整理', 'scene'), (null, '时间管理', 'scene'), (null, 'AI', 'scene'),
  (null, '社交', 'scene'), (null, '其他', 'scene'),
  (null, '重复操作', 'problem'), (null, '信息整理', 'problem'), (null, '判断困难', 'problem'),
  (null, '容易忘', 'problem'), (null, '数据处理', 'problem'), (null, '文件处理', 'problem'),
  (null, '搜索', 'problem'), (null, '计划', 'problem'), (null, '追踪', 'problem'),
  (null, '提醒', 'problem'), (null, '自动化', 'problem'), (null, '决策', 'problem')
on conflict do nothing;

commit;
